import { Open_Sans, Fira_Mono } from "next/font/google";
import "./globals.css";

// Import Open Sans and Fira Mono from Google Fonts
const openSans = Open_Sans({
  subsets: ["latin"],
  variable: "--font-open-sans",
  weight: ["400", "600", "700"],
});

const firaMono = Fira_Mono({
  subsets: ["latin"],
  variable: "--font-fira-mono",
  weight: ["400", "500", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${openSans.variable} ${firaMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
